// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package persistence

import (
	types "github.com/STBoyden/go-portfolio/internal/pkg/common/types"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        uuid.UUID         `json:"id"`
	CreatedAt pgtype.Timestamp  `json:"created_at"`
	Slug      string            `json:"slug"`
	Content   types.BlogContent `json:"content"`
}
