name: golangci-lint
on:
  push:
    branches:
      - develop
      - feature/**/*
      - hotfix/**/*
      - bugfix/**/*
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: prepare repository for CI linting
        run: just ci_prepare

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          args: --build-tags ci
